# Generated by Django 4.2.8 on 2024-01-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0002_auto_20231227_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
