# Generated by Django 4.2.8 on 2024-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0003_item_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatus',
            name='deadline',
            field=models.BooleanField(default=False),
        ),
    ]
