# Generated by Django 4.2.7 on 2023-11-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0004_itemstatus_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
