# Generated by Django 4.2.8 on 2024-02-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0005_entitytype_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
