# Generated by Django 4.2.7 on 2023-11-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0005_remove_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='entity',
            name='postalcode',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
