# Generated by Django 4.2.8 on 2024-02-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0006_entity_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
