# Generated by Django 4.2.7 on 2023-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0006_item_author_alter_entity_country_alter_entity_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('valid', models.BooleanField(default=True)),
                ('parents', models.ManyToManyField(to='ne_sop_api.itemtype')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
