# Generated by Django 4.2.7 on 2023-11-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0008_document_uuid_entity_uuid_event_uuid_item_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created',
        ),
    ]
