# Generated by Django 4.2.8 on 2025-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0008_alter_document_author_alter_item_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='item',
        ),
        migrations.AddField(
            model_name='document',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='documents', to='ne_sop_api.item'),
        ),
    ]
