# Generated by Django 4.2.8 on 2025-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0010_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
