# Generated by Django 4.2.8 on 2025-02-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0012_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ne_sop_api.documenttype'),
        ),
    ]
