# Generated by Django 4.2.7 on 2023-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0013_item_lead_item_support_alter_event_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oralresponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='writtenresponse',
            field=models.BooleanField(default=False),
        ),
    ]
