# Generated by Django 5.0 on 2023-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ne_sop_api", "0014_item_oralresponse_item_writtenresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="content",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="item",
            name="support",
            field=models.ManyToManyField(
                blank=True, related_name="support", to="ne_sop_api.entity"
            ),
        ),
    ]
