# Generated by Django 5.0 on 2023-12-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0015_rename_parents_template_item_types_document_relpath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.AddField(
            model_name='document',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ne_sop_api.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.template'),
        ),
    ]
