# Generated by Django 5.0 on 2023-12-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0015_rename_content_item_description_alter_item_support'),
        ('ne_sop_api', '0016_remove_document_date_document_item_document_template'),
    ]

    operations = [
    ]
