# Generated by Django 4.2.8 on 2023-12-19 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0018_document_author_document_size_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.entity'),
        ),
        migrations.AlterField(
            model_name='document',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ne_sop_api.item'),
        ),
        migrations.CreateModel(
            name='NewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('filename', models.CharField(default=None, max_length=200)),
                ('version', models.PositiveIntegerField(default=None)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_documents', to='ne_sop_api.item')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.template')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
