# Generated by Django 4.2.8 on 2023-12-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0018_document_author_document_size_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ne_sop_api.entity'),
        ),
    ]
