# Generated by Django 4.2.8 on 2023-12-20 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ne_sop_api', '0019_item_enddate_item_startdate_alter_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
