# Generated by Django 4.2.8 on 2023-12-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0019_alter_document_author_alter_document_item_and_more'),
        ('ne_sop_api', '0019_item_enddate_item_startdate_alter_document_author'),
    ]

    operations = [
    ]
