# Generated by Django 4.2.8 on 2023-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0020_entity_users'),
        ('ne_sop_api', '0020_merge_20231220_1010'),
    ]

    operations = [
    ]
