# Generated by Django 4.2.8 on 2023-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0021_item_autonotify_alter_entity_type_alter_entity_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='autonotify',
            field=models.BooleanField(default=False),
        ),
    ]
