# Generated by Django 4.2.8 on 2023-12-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ne_sop_api.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ne_sop_api', '0021_merge_0020_entity_users_0020_merge_20231220_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RenameModel('NewDocument', 'Document'),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ne_sop_api.entitytype'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ne_sop_api.eventtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ne_sop_api.itemstatus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='support',
            field=models.ManyToManyField(blank=True, related_name='item', to='ne_sop_api.entity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ne_sop_api.itemtype'),
        ),
    ]
