# Generated by Django 4.2.8 on 2023-12-22 14:48

from django.db import migrations, models
import django.db.models.deletion
import ne_sop_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0022_remove_document_relpath_remove_document_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=ne_sop_api.utils.Utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ne_sop_api.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-22 15:48:00'),
            preserve_default=False,
        ),
    ]
