# Generated by Django 4.2.8 on 2023-12-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0022_alter_item_autonotify'),
        ('ne_sop_api', '0023_alter_document_file_alter_document_item_and_more'),
    ]

    operations = [
    ]
