# Generated by Django 4.2.8 on 2023-12-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ne_sop_api', '0024_merge_20231222_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
