# Generated by Django 4.2.8 on 2023-12-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_sop_api', '0022_auto_20231220_1634'),
        ('ne_sop_api', '0025_alter_entity_users'),
    ]

    operations = [
    ]
